defmodule SmsSchool.Repo.Migrations.AddUniqueKeyClassTypePerClass do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:class_types) do
      modify :class_id, :uuid
    end

    create index(:class_types, [:class_id])

    create unique_index(:class_types, [:name, :class_id],
             name: "class_types_unique_class_type_name_per_class_index"
           )
  end

  def down do
    drop_if_exists unique_index(:class_types, [:name, :class_id],
                     name: "class_types_unique_class_type_name_per_class_index"
                   )

    drop_if_exists index(:class_types, [:class_id])

    alter table(:class_types) do
      modify :class_id, :uuid
    end
  end
end
