defmodule SmsSchool.Repo.Migrations.AddTableClassType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:class_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :class_id,
          references(:classes,
            column: :id,
            name: "class_types_class_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:class_types, "class_types_class_id_fkey")

    drop table(:class_types)
  end
end
