defmodule SmsSchool.Repo.Migrations.CreateTable_Village do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:villages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :commune_id,
          references(:communes,
            column: :id,
            name: "villages_commune_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:villages, [:commune_id])
  end

  def down do
    drop_if_exists index(:villages, [:commune_id])

    drop constraint(:villages, "villages_commune_id_fkey")

    drop table(:villages)
  end
end
