defmodule SmsSchool.Repo.Migrations.AddReferentForClassTypeClass do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:class_types, "class_types_class_id_fkey")

    alter table(:class_types) do
      modify :class_id,
             references(:classes,
               column: :id,
               name: "class_types_class_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:class_types, "class_types_class_id_fkey")

    alter table(:class_types) do
      modify :class_id,
             references(:classes,
               column: :id,
               name: "class_types_class_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
