defmodule SmsSchool.Repo.Migrations.AddUnineForStudent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:students, ["first_name last_name gin_trgm_ops"],
                     name: "students_name_gin_index"
                   )

    create index(:students, ["last_name gin_trgm_ops"],
             name: "students_last_name_gin_index",
             using: "GIN"
           )

    create index(:students, ["first_name gin_trgm_ops"],
             name: "students_first_name_gin_index",
             using: "GIN"
           )
  end

  def down do
    drop_if_exists index(:students, ["first_name gin_trgm_ops"],
                     name: "students_first_name_gin_index"
                   )

    drop_if_exists index(:students, ["last_name gin_trgm_ops"],
                     name: "students_last_name_gin_index"
                   )

    create index(:students, ["first_name last_name gin_trgm_ops"],
             name: "students_name_gin_index",
             using: "GIN"
           )
  end
end
