defmodule SmsSchool.Repo.Migrations.CreateTable_Commune do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:communes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :district_id,
          references(:districts,
            column: :id,
            name: "communes_district_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:communes, [:district_id])
  end

  def down do
    drop_if_exists index(:communes, [:district_id])

    drop constraint(:communes, "communes_district_id_fkey")

    drop table(:communes)
  end
end
