defmodule SmsSchool.Repo.Migrations.AddEmplyeeJob do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :description, :text

      add :employee_id,
          references(:employees,
            column: :id,
            name: "jobs_employee_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:jobs, [:employee_id])
  end

  def down do
    drop_if_exists index(:jobs, [:employee_id])

    drop constraint(:jobs, "jobs_employee_id_fkey")

    drop table(:jobs)
  end
end
