defmodule SmsSchool.Repo.Migrations.AddUniqeForDistrict do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:districts, ["name gin_trgm_ops"],
             name: "districts_name_gin_index",
             using: "GIN"
           )
  end

  def down do
    drop_if_exists index(:districts, ["name gin_trgm_ops"], name: "districts_name_gin_index")
  end
end
