defmodule SmsSchool.Repo.Migrations.CreateTableEmployee do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:employees, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :gender, :text, null: false
      add :dob, :date, null: false
      add :phone, :text, null: false
      add :image, :text
    end
  end

  def down do
    drop table(:employees)
  end
end
