defmodule SmsSchool.Repo.Migrations.AdUniqeForProvine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:provies, ["name gin_trgm_ops"], name: "provies_name_gin_index", using: "GIN")
  end

  def down do
    drop_if_exists index(:provies, ["name gin_trgm_ops"], name: "provies_name_gin_index")
  end
end
