defmodule SmsSchool.Repo.Migrations.AddGinIndexForClassTypeNameSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:class_types, ["name gin_trgm_ops"],
             name: "class_type_name_gin_index",
             using: "GIN"
           )
  end

  def down do
    drop_if_exists index(:class_types, ["name gin_trgm_ops"], name: "class_type_name_gin_index")
  end
end
