defmodule SmsSchool.Repo.Migrations.CreateTable_Student_Adress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:student_addresses, primary_key: false) do
      add :id, :uuid

      add :student_id,
          references(:students,
            column: :id,
            name: "student_addresses_student_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :village_id,
          references(:villages,
            column: :id,
            name: "student_addresses_village_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:student_addresses, [:student_id])

    create index(:student_addresses, [:village_id])
  end

  def down do
    drop_if_exists index(:student_addresses, [:village_id])

    drop_if_exists index(:student_addresses, [:student_id])

    drop constraint(:student_addresses, "student_addresses_student_id_fkey")

    drop constraint(:student_addresses, "student_addresses_village_id_fkey")

    drop table(:student_addresses)
  end
end
