defmodule SmsSchool.Repo.Migrations.AddUniqeForEmployee do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:employees, ["last_name gin_trgm_ops"],
             name: "employee_last_name_gin_index",
             using: "GIN"
           )

    create index(:employees, ["first_name gin_trgm_ops"],
             name: "employee_first_name_gin_index",
             using: "GIN"
           )
  end

  def down do
    drop_if_exists index(:employees, ["first_name gin_trgm_ops"],
                     name: "employee_first_name_gin_index"
                   )

    drop_if_exists index(:employees, ["last_name gin_trgm_ops"],
                     name: "employee_last_name_gin_index"
                   )
  end
end
